
title: Özlem Ekici
email: ozlemekici9774@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ozlemekici

# Build settings
theme: minima
plugins:
  - jekyll-feed

texture:
  title: Özlem Ekici
  tagline: Physics Engineer - Developer - Photographer
  date_format: "%b %-d, %Y"
  style: black
 


  navigation:
    - title: Main Page
      url: "/"
    - title: About
      url: "/about"


  social_links:
    github:  ozlemekici
    linkedIn: in/ozlemekici # format: locale/username
