
title: Özlem Ekici
email: ozlemekici9774@gmail.com
description: Personal Website # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ozlemekici

# Build settings
theme: minima
plugins:
  - jekyll-feed

texture:
  title: Özlem Ekici
  tagline: Data Analyst | Power BI Expert | Python Developer   
  date_format: "%b %-d, %Y"
  style: black
 
  navigation:
    - title: Main Page
      url: "/"
    - title: About
      url: "/about"

  social_links:
    github:  ozlemekici
    linkedIn: in/ozlemekici   # format: locale/username
    twitter: levlapad
